services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerContext: ./BackEnd
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: your-mysql-host.com
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password

      - key: REDIS_HOST
        value: your-redis-host.com
      - key: REDIS_PORT
        value: 6379

      - key: KAFKA_BOOTSTRAP_SERVERS
        value: your-kafka-bootstrap.com:9092

      # Email
      - key: SPRING_MAIL_HOST
        fromEnvVar: SPRING_MAIL_HOST
      - key: SPRING_MAIL_PORT
        fromEnvVar: SPRING_MAIL_PORT
      - key: SPRING_MAIL_USERNAME
        fromEnvVar: SPRING_MAIL_USERNAME
      - key: SPRING_MAIL_PASSWORD
        fromEnvVar: SPRING_MAIL_PASSWORD
      - key: SPRING_MAIL_FROM
        fromEnvVar: SPRING_MAIL_FROM

      # JWT
      - key: JWT_SIGNER_KEY
        fromEnvVar: JWT_SIGNER_KEY
      - key: JWT_VALID_DURATION
        fromEnvVar: JWT_VALID_DURATION
      - key: JWT_REFRESHABLE_DURATION
        fromEnvVar: JWT_REFRESHABLE_DURATION

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        fromEnvVar: GOOGLE_CLIENT_ID
      - key: GOOGLE_SECRET
        fromEnvVar: GOOGLE_SECRET
      - key: GOOGLE_REDIRECT_URL
        fromEnvVar: GOOGLE_REDIRECT_URL
      - key: GOOGLE_SCOPE
        fromEnvVar: GOOGLE_SCOPE
      - key: USER_INFO_URI
        fromEnvVar: USER_INFO_URI

      # AI API
      - key: API_URL
        fromEnvVar: API_URL
      - key: API_KEY
        fromEnvVar: API_KEY

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerContext: ./FrontEnd
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend.onrender.com
